RequestNetwork/Request_App

src/app/util/web3.service.ts

This should fix the issue with requesting too high an amount for approval.

Remove extraneous call to amountToBN

---

src/app/invoices/home/home.component.html
src/app/invoices/invoices.component.html
src/app/invoices/invoices.component.ts
src/app/invoices/request/request.component.html
src/app/pay-with-request/pay-with-request.component.ts
src/app/shared/account/account.component.html
src/app/shared/request-addresses/request-addresses.component.html
src/app/util/dialogs/pay-dialog.component.ts
src/assets/js/mobile.js
src/index.html
src/styles.scss

This is on staging
Test: 
view staging link - should look good on mobile
If your not on a web3 compatible dApp browser + on mobile there is a new popup which redirects to Trust / MM. When dismissed it should not return (unless cookies are cleared). 
Download Trust / MM for full testing if required.

feat: mobile compatibility, also added support for Trust Wallet and Metamask Mobile

---

src/index.html

feat: change title

---

src/app/invoices/request/request.component.html
src/app/shared/currency-converter/currency-converter.component.ts
src/app/shared/request-amount/request-amount.component.html
src/styles.scss

we check cryptocompare based on the UpdatedExpectedAmount event timestamp to get the amount is USD at the time of paid.

feat: added usd value at the time of paid

---

src/app/invoices/request/request.component.html
src/app/invoices/request/request.component.ts

Conversion made as of:
- Request creation date if unpaid
- Payment date if paid
Fixed a but that was showing the same converted amount several times in case of multiple payments

At-92 USD value of amount

---

package-lock.json
package.json
src/app/app.module.ts
src/app/invoices/currency-selector/currency-selector.component.ts
src/app/invoices/home/home.component.ts
src/app/invoices/invoices.component.html
src/app/invoices/request/request.component.html
src/app/invoices/request/request.component.ts
src/app/invoices/search/search.component.html
src/app/invoices/search/search.component.ts
src/app/shared/pending-requests/pending-requests.component.html
src/app/shared/pending-requests/pending-requests.component.ts
src/app/shared/shared.module.ts
src/app/util/util.service.ts
src/app/util/web3.service.ts
src/index.html
src/styles.scss

Sorry for the big PR - this should have been broken down into several smaller PRs but the modules were tightly coupled (notifications etc)

feat: AT-77 pending requests

---

src/assets/js/receipt.js

According to: https://github.com/MrRio/jsPDF/issues/2080

fix:PDF download for mobile applications

---

src/app/shared/request-address/request-address.component.html
src/app/shared/request-addresses/request-addresses.component.html
src/assets/js/receipt.js

Added address with labels in PDF

feat: At 96 pdf labels

---

src/app/shared/account/account.component.html

* fix:Show the Metamask connection button after logging out without page refresh
* fix: replace the loader with a MM connection button

feat:At 118 logging in and out of metamask (#62)

---

src/app/invoices/request/rnf-invoice/rnf-invoice.component.scss

fix: invoice overflow fixes

---

src/app/invoices/search/search.component.html
src/app/invoices/search/search.component.ts

* Add status
* Improve behavior for 2 requests having the same from / to / amount / status

refactor:At 151 dashboard sorting

---

src/app/shared/address-book/address-book.component.html
src/app/shared/address-book/address-book.component.scss

* 20 characters maximum
* No use feedback when he reaches this limit
* The error message shows nicely when a former name was set with a name too long

feat:At 156 max label length

---

src/app/util/web3.service.ts

Adding @AdamDowson for information about the comments. It is the same behavior as Compound now and I believe the best possible with Metamask at the moment.

fix:At162 metamask locked

---

src/app/invoices/advanced-invoice/advanced-invoice.component.html
src/app/invoices/advanced-invoice/advanced-invoice.component.ts
src/app/invoices/home/home.component.html
src/app/invoices/request/request.component.html
src/app/invoices/request/request.component.ts
src/app/invoices/request/rnf-invoice/rnf-invoice.component.html
src/styles.scss

As per the ticket, bugs found during QA.

fix: conversion bug, create invoice button,

---

src/app/invoices/request/request.component.html
src/assets/js/receipt.js
src/index.html

Tried several methods to achieve this, looked into some server-side tools but decided to keep it simple for now using jsPDF.

feat: At-154 - receipt generation for invoices

---

src/app/invoices/search/search.component.html
src/app/invoices/search/search.component.scss
src/app/invoices/search/search.component.ts
src/styles.scss

Quick-win mode, not a proper mobile UX but at least the relevant data fits on screen

feat: Mobile dashboard

---

src/app/invoices/home/home.component.html
src/app/invoices/home/home.component.ts
src/app/invoices/request/request.component.ts
src/app/invoices/request/rnf-invoice/rnf-invoice.component.ts
src/app/invoices/search/search.component.ts
src/app/shared/CSV-export/CSV-export.component.ts
src/app/shared/address-book/address-book.component.ts
src/app/shared/short-address.pipe.ts
src/app/util/web3.service.ts
src/styles.scss

Format run
CSV export bug with builderID 
CSS added for CSV import button (in modal)

fix: dashboard variable widths on desktop, tidyup / bug fixes

---

src/app/invoices/search/search.component.scss

fix: remove orange border from dashboard

---

src/app/invoices/search/search.component.html
src/app/invoices/search/search.component.scss
src/styles.scss

* Also improve CSS separation between search results and global elements

fix:Main container width back to its previous value

---

.circleci/config.yml
src/app/invoices/home/home.component.html
src/app/invoices/home/home.component.scss

Removed this link as per brices request

fix: remove invoice link

---

src/app/util/gas.service.ts

added api key for ethgasstation

feat: add api key for ethgasstation

---

src/app/invoices/invoices.component.html
src/app/shared/create/create.component.html
src/app/shared/create/create.component.scss
src/app/shared/create/create.component.ts
src/app/shared/shared.module.ts

feat: add modal for create redirect
